function [Rate_on_mean]=data_reduction(Rate_on,StringFunc)

if strcmp(StringFunc,'mean')
    Rate_on_mean=[mean(getfield(Rate_on,'Presleep'))...
    mean(getfield(Rate_on,'Post_Trial_1'))...
    mean(getfield(Rate_on,'Post_Trial_2'))...
    mean(getfield(Rate_on,'Post_Trial_3'))...
    mean(getfield(Rate_on,'Post_Trial_4'))...
    mean(getfield(Rate_on,'Post_Trial_5_1'))...
    mean(getfield(Rate_on,'Post_Trial_5_2'))...
    mean(getfield(Rate_on,'Post_Trial_5_3'))...
    mean(getfield(Rate_on,'Post_Trial_5_4'))...
    
    ];
elseif strcmp(StringFunc,'sum')
    Rate_on_mean=[sum(getfield(Rate_on,'Presleep'))...
    sum(getfield(Rate_on,'Post_Trial_1'))...
    sum(getfield(Rate_on,'Post_Trial_2'))...
    sum(getfield(Rate_on,'Post_Trial_3'))...
    sum(getfield(Rate_on,'Post_Trial_4'))...
    sum(getfield(Rate_on,'Post_Trial_5_1'))...
    sum(getfield(Rate_on,'Post_Trial_5_2'))...
    sum(getfield(Rate_on,'Post_Trial_5_3'))...
    sum(getfield(Rate_on,'Post_Trial_5_4'))...

    ];
    
    
else
    error('Something is wrong');
end

end